name = "uxstrings"
description = "Unicode Extended Strings utilities"
version = "21.02.07"
tags = ["unicode", "dynamic", "string"]

authors = ["Pascal Pignard"]
maintainers = ["Pascal Pignard <blady.net@orange.fr>"]
maintainers-logins = ["Blady-Com"]
website = "https://github.com/Blady-Com/UXStrings"

licenses = "CECILL-2.1"

project-files = ["lib_uxstrings1.gpr"]

[[depends-on]]
gnat = ">=2020"
