name = "uxstrings"
description = "Unicode Extended Strings utilities"
version = "0.8.2+alpha-20250125"
tags = ["unicode", "dynamic", "string"]

authors = ["Pascal Pignard"]
maintainers = ["Pascal Pignard <blady.net@orange.fr>"]
maintainers-logins = ["Blady-Com"]
website = "https://github.com/Blady-Com/UXStrings"

licenses = "CECILL-C"

project-files = ["lib_uxstrings.gpr"]

[[depends-on]]
gnat = "^13.0"
# Put in comment since dependancies of SC puzzled Alire
# simple_components = "^4.62.0"
